#!/usr/bin/env python
"""Round22 P0 route dry run for verified/literature-backed candidates.

Audit-only. This script asks whether Round21 P0 source-backed positives can be
generated by current rule paths. It does not write training data, model files, or
production generator changes.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd
from rdkit import Chem
from rdkit import RDLogger


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "curation"
DOC = ROOT / "docs" / "reviews" / "round22_p0_route_dryrun.md"
POOL = Path(r"D:\CRB\FoodGut\positive_sample_db\data\processed\foodgut_modular_positive_candidate_pool_v2.csv")
LTR_OUT = ROOT / "outputs" / "modular" / "ltr"

sys.path.insert(0, str(ROOT / "modular"))
sys.path.insert(0, str(ROOT / "src"))
import kio  # noqa: E402
from generate_candidates import run_reactants  # noqa: E402
from ltr_candidates import load_module_rules  # noqa: E402


RDLogger.DisableLog("rdApp.*")

TARGET_RULE_COLUMNS = [
    "round",
    "candidate_id",
    "rule_variant",
    "target_rule_hashes",
    "target_ec_classes",
    "target_reaction_types",
    "target_source_datasets",
    "training_allowed_round22",
]

DECOY_COLUMNS = [
    "round",
    "candidate_id",
    "rule_variant",
    "substrate_name",
    "decoy_pb",
    "decoy_product_smiles",
    "decoy_ec_classes",
    "decoy_rule_hashes",
    "decoy_status_round22",
    "training_allowed_round22",
]

MACRO2MOD = {
    "small_molecule_polyphenol": "A",
    "carbohydrate_glycan": "B",
    "protein_amino_acid": "C",
    "lipid_fat": "D",
}


def ec_class(ec: object) -> int:
    text = "" if pd.isna(ec) else str(ec)
    return int(text[0]) if text[:1].isdigit() else 0


def joined(values: Iterable[object], limit: int | None = None) -> str:
    vals = sorted({str(v) for v in values if pd.notna(v) and str(v) != ""})
    if limit is not None:
        vals = vals[:limit]
    return ";".join(vals)


def rule_hash(smarts: str) -> str:
    return hashlib.sha1(str(smarts).encode("utf-8")).hexdigest()[:12]


def key_block1(smiles: str) -> str:
    return kio.inchikey_block1(kio.smiles_to_inchikey(smiles))


def load_pool_rules() -> pd.DataFrame:
    usecols = [
        "macro_module",
        "reaction_rule_smarts",
        "enzyme_ec",
        "source_dataset",
        "source_origin_type",
        "reaction_category",
        "reaction_type",
        "reaction_rule_id",
    ]
    rules = pd.read_csv(POOL, low_memory=False, usecols=lambda c: c in usecols)
    rules["module"] = rules["macro_module"].map(MACRO2MOD)
    rules = rules.dropna(subset=["module", "reaction_rule_smarts"])
    rules = rules[rules["reaction_rule_smarts"].astype(str).str.contains(">>", regex=False)].copy()
    rules["ecc"] = rules["enzyme_ec"].map(ec_class)
    rules["rule_hash"] = rules["reaction_rule_smarts"].map(rule_hash)
    rules = rules.sort_values(["module", "ecc", "reaction_rule_smarts"], ascending=[True, False, True])
    return rules.drop_duplicates(["module", "reaction_rule_smarts"])


def sampled_rules() -> pd.DataFrame:
    sampled = load_module_rules(np.random.default_rng(0), 800)
    rows = []
    for module, rules in sampled.items():
        for smarts, ecc in rules:
            rows.append(
                {
                    "module": module,
                    "reaction_rule_smarts": smarts,
                    "ecc": int(ecc),
                    "rule_hash": rule_hash(smarts),
                    "source_dataset": "sampled_positive_pool",
                    "source_origin_type": "sampled_positive_pool",
                    "reaction_category": "",
                    "reaction_type": "",
                    "reaction_rule_id": "",
                }
            )
    return pd.DataFrame(rows)


def rule_variants() -> dict[str, pd.DataFrame]:
    sampled = sampled_rules()
    pool = load_pool_rules()
    return {
        "sampled_all_800": sampled,
        "sampled_require_ec_800": sampled[sampled["ecc"].ne(0)].copy(),
        "all_pool_all_rules": pool,
        "all_pool_require_ec": pool[pool["ecc"].ne(0)].copy(),
    }


def run_rule_table(rules: pd.DataFrame, substrate_smiles: str) -> dict[str, dict[str, object]]:
    mol = Chem.MolFromSmiles(substrate_smiles)
    if mol is None:
        return {}
    molh = Chem.AddHs(mol)
    generated: dict[str, dict[str, object]] = {}
    for row in rules.itertuples(index=False):
        for product_smiles in run_reactants(row.reaction_rule_smarts, mol, molh):
            pb = key_block1(product_smiles)
            if not pb:
                continue
            if pb not in generated:
                generated[pb] = {
                    "product_smiles": product_smiles,
                    "ec_classes": set(),
                    "rule_hashes": set(),
                    "reaction_types": set(),
                    "source_datasets": set(),
                }
            generated[pb]["ec_classes"].add(int(row.ecc))
            generated[pb]["rule_hashes"].add(str(row.rule_hash))
            generated[pb]["reaction_types"].add(str(row.reaction_type))
            generated[pb]["source_datasets"].add(str(row.source_dataset))
    return generated


def build_dryrun() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    worklist = pd.read_csv(OUT / "round21_p0_collection_worklist.csv")
    reactions = pd.read_parquet(LTR_OUT / "reactions.parquet")
    reactions["_pair_key"] = (
        reactions["module"].astype(str) + "__" + reactions["sb"].astype(str) + "__" + reactions["pb"].astype(str)
    )
    true_products = reactions.groupby(["module", "sb"])["pb"].agg(set).to_dict()
    variants = rule_variants()
    rows = []
    target_rule_rows = []
    decoy_rows = []
    for candidate in worklist.itertuples(index=False):
        truth = true_products.get((candidate.module, candidate.sb), set())
        for variant_name, all_rules in variants.items():
            rules = all_rules[all_rules["module"].eq(candidate.module)].copy()
            generated = run_rule_table(rules, candidate.substrate_smiles)
            target = generated.get(candidate.pb)
            target_generated = target is not None
            decoys = sorted(pb for pb in generated if pb not in truth and pb != candidate.sb)
            generated_truth = sorted(pb for pb in generated if pb in truth)
            route_decision = "target_not_generated_by_this_variant"
            if str(candidate.verification_status_round21).startswith("blocked"):
                route_decision = "evidence_blocked_before_route_repair"
            elif target_generated and "require_ec" in variant_name:
                route_decision = "target_generates_under_require_ec_route"
            elif target_generated:
                route_decision = "target_generates_without_require_ec_ec_provenance_gate_needed"
            rows.append(
                {
                    "round": 22,
                    "candidate_id": candidate.candidate_id,
                    "module": candidate.module,
                    "substrate_name": candidate.substrate_name,
                    "product_name": candidate.product_name,
                    "verification_status_round21": candidate.verification_status_round21,
                    "rule_variant": variant_name,
                    "rule_count": len(rules),
                    "generated_product_count": len(generated),
                    "generated_truth_products": joined(generated_truth),
                    "target_generated": target_generated,
                    "target_ec_classes": joined(target["ec_classes"]) if target else "",
                    "target_rule_hashes": joined(target["rule_hashes"], limit=20) if target else "",
                    "target_source_datasets": joined(target["source_datasets"], limit=8) if target else "",
                    "decoy_count": len(decoys),
                    "decoy_preview_pb": joined(decoys, limit=12),
                    "final_clean_eligible_in_dryrun": bool(target_generated and len(decoys) > 0 and "require_ec" in variant_name),
                    "route_decision_round22": route_decision,
                    "training_allowed_round22": False,
                }
            )
            if target_generated:
                target_rule_rows.append(
                    {
                        "round": 22,
                        "candidate_id": candidate.candidate_id,
                        "rule_variant": variant_name,
                        "target_rule_hashes": joined(target["rule_hashes"]),
                        "target_ec_classes": joined(target["ec_classes"]),
                        "target_reaction_types": joined(target["reaction_types"], limit=20),
                        "target_source_datasets": joined(target["source_datasets"], limit=20),
                        "training_allowed_round22": False,
                    }
                )
            for pb in decoys[:50]:
                rec = generated[pb]
                decoy_rows.append(
                    {
                        "round": 22,
                        "candidate_id": candidate.candidate_id,
                        "rule_variant": variant_name,
                        "substrate_name": candidate.substrate_name,
                        "decoy_pb": pb,
                        "decoy_product_smiles": rec["product_smiles"],
                        "decoy_ec_classes": joined(rec["ec_classes"]),
                        "decoy_rule_hashes": joined(rec["rule_hashes"], limit=8),
                        "decoy_status_round22": "unlabeled_decoy_screen_against_external_sources_before_training",
                        "training_allowed_round22": False,
                    }
                )
    target_rules = pd.DataFrame(target_rule_rows, columns=TARGET_RULE_COLUMNS)
    decoys = pd.DataFrame(decoy_rows, columns=DECOY_COLUMNS)
    return pd.DataFrame(rows), target_rules, decoys


def build_decisions(dryrun: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for candidate_id, group in dryrun.groupby("candidate_id", sort=False):
        first = group.iloc[0]
        if str(first["verification_status_round21"]).startswith("blocked"):
            decision = "do_not_route_repair_until_evidence_recurated"
            next_gate = "fix source evidence mismatch or external verification first"
        elif group[group["rule_variant"].str.contains("require_ec")]["target_generated"].any():
            decision = "route_repair_candidate_require_ec_generation_available"
            next_gate = "inspect target rules; screen decoys; then code-review integration"
        elif group["target_generated"].any():
            decision = "ec_provenance_gate_blocks_final_clean"
            next_gate = "attach source-backed EC/provenance or create explicit literature-backed overlay"
        else:
            decision = "rule_family_missing_for_current_generator"
            next_gate = "derive/source rule from verified reaction family before importing more positives"
        rows.append(
            {
                "round": 22,
                "candidate_id": candidate_id,
                "substrate_name": first["substrate_name"],
                "product_name": first["product_name"],
                "verification_status_round21": first["verification_status_round21"],
                "any_target_generated": bool(group["target_generated"].any()),
                "require_ec_target_generated": bool(group[group["rule_variant"].str.contains("require_ec")]["target_generated"].any()),
                "max_decoy_count": int(group["decoy_count"].max()),
                "decision_round22": decision,
                "next_gate": next_gate,
                "training_allowed_round22": False,
            }
        )
    return pd.DataFrame(rows)


def write_doc(dryrun: pd.DataFrame, decisions: pd.DataFrame) -> None:
    DOC.parent.mkdir(parents=True, exist_ok=True)
    summary = decisions["decision_round22"].value_counts().reset_index()
    summary.columns = ["decision_round22", "count"]
    text = "# Round22 P0 Route Dry Run\n\n"
    text += "## Working conclusion\n\n"
    text += (
        "Round22 tests whether Round21 source-backed positives are generator-route failures. "
        "Training remains blocked for every candidate. A candidate can only advance after exact evidence, target generation, "
        "and external decoy screening all pass.\n\n"
    )
    text += "## Decision counts\n\n```text\n"
    text += summary.to_string(index=False)
    text += "\n```\n\n"
    text += "## Candidate decisions\n\n```text\n"
    cols = [
        "candidate_id",
        "substrate_name",
        "product_name",
        "any_target_generated",
        "require_ec_target_generated",
        "max_decoy_count",
        "decision_round22",
        "training_allowed_round22",
    ]
    text += decisions[cols].to_string(index=False)
    text += "\n```\n\n"
    text += "## Variant target generation\n\n```text\n"
    variant_cols = ["rule_variant", "target_generated", "final_clean_eligible_in_dryrun"]
    variant_summary = dryrun.groupby("rule_variant").agg(
        targets_generated=("target_generated", "sum"),
        final_clean_eligible=("final_clean_eligible_in_dryrun", "sum"),
        candidates=("candidate_id", "nunique"),
    ).reset_index()
    text += variant_summary.to_string(index=False)
    text += "\n```\n\n"
    text += "## Written artifacts\n\n"
    text += "- `data/curation/round22_p0_route_dryrun.csv`\n"
    text += "- `data/curation/round22_target_generating_rules.csv`\n"
    text += "- `data/curation/round22_decoy_screening_manifest.csv`\n"
    text += "- `data/curation/round22_p0_route_decisions.csv`\n"
    DOC.write_text(text, encoding="utf-8")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    dryrun, target_rules, decoys = build_dryrun()
    decisions = build_decisions(dryrun)
    outputs = {
        "round22_p0_route_dryrun.csv": dryrun,
        "round22_target_generating_rules.csv": target_rules,
        "round22_decoy_screening_manifest.csv": decoys,
        "round22_p0_route_decisions.csv": decisions,
    }
    for name, df in outputs.items():
        path = OUT / name
        df.to_csv(path, index=False)
        print(f"wrote {path.relative_to(ROOT)} rows={len(df)}")
    write_doc(dryrun, decisions)
    print(f"wrote {DOC.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
