from __future__ import annotations

import json
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
CUR = ROOT / "data" / "curation"
ROUND = "round23"


def read_table(path: Path) -> pd.DataFrame:
    if path.suffix == ".parquet":
        return pd.read_parquet(path)
    return pd.read_csv(path)


def write_csv(df: pd.DataFrame, rel: str) -> Path:
    path = ROOT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)
    return path


def load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def rhea_summary(file_name: str) -> tuple[int, str, str]:
    data = load_json(CUR / "rhea_round23_raw" / file_name)
    results = data.get("results") or []
    ids = []
    eqs = []
    for item in results:
        rid = str(item.get("id", "")).strip()
        equation = str(item.get("equation", "")).strip()
        if rid:
            ids.append(f"RHEA:{rid}")
        if equation:
            eqs.append(equation)
    return int(data.get("count", len(results)) or 0), "; ".join(ids), "; ".join(eqs[:3])


def pubmed_titles(file_name: str, max_titles: int = 4) -> tuple[str, str]:
    data = load_json(CUR / "ncbi_round23_raw" / file_name)
    result = data.get("result") or {}
    uids = result.get("uids") or []
    titles = []
    for uid in uids[:max_titles]:
        item = result.get(str(uid), {})
        title = str(item.get("title", "")).strip()
        pubdate = str(item.get("pubdate", "")).strip()
        if title:
            titles.append(f"{uid} ({pubdate}): {title}")
    return "; ".join(map(str, uids)), " | ".join(titles)


def build_current_blocker_audit() -> pd.DataFrame:
    raw_path = Path(
        r"D:\CRB\FoodGut\positive_sample_db\data\processed"
        r"\foodgut_modular_positive_candidate_pool_v2.csv"
    )
    reactions = read_table(ROOT / "outputs/modular/ltr/reactions.parquet")
    pairs = read_table(ROOT / "outputs/modular/ltr/pairs.parquet")
    clean_full = read_table(ROOT / "outputs/modular/ltr/clean_candidates_full.parquet")
    clean = read_table(ROOT / "outputs/modular/ltr/clean_candidates.parquet")
    metrics = read_table(ROOT / "outputs/modular/ltr/clean2_metrics.csv")
    route = read_table(CUR / "round22_p0_route_dryrun.csv")
    p0 = read_table(CUR / "round21_p0_collection_worklist.csv")

    raw_rows = len(pd.read_csv(raw_path, low_memory=False)) if raw_path.exists() else None
    rows = [
        {
            "round": ROUND,
            "evidence_item": "raw_positive_pool_rows",
            "value": raw_rows,
            "source_path": str(raw_path),
            "audit_meaning": "Raw positive rows before ltr_build filters and deduplication.",
            "production_interpretation": "Not the training/evaluation sample count by itself.",
        },
        {
            "round": ROUND,
            "evidence_item": "unique_positive_reactions",
            "value": len(reactions),
            "source_path": "outputs/modular/ltr/reactions.parquet",
            "audit_meaning": "Unique positive pairs after current ltr_build-style reaction deduplication.",
            "production_interpretation": "This is the main positive pool before deployment-faithful rule generation.",
        },
        {
            "round": ROUND,
            "evidence_item": "reaction_tier_counts",
            "value": reactions["tier"].value_counts().to_dict(),
            "source_path": "outputs/modular/ltr/reactions.parquet",
            "audit_meaning": "Gold is small compared with silver/weak.",
            "production_interpretation": "External generalization is not proven by a large weak/silver pool.",
        },
        {
            "round": ROUND,
            "evidence_item": "pairs_pos_neg",
            "value": pairs["y"].value_counts().to_dict(),
            "source_path": "outputs/modular/ltr/pairs.parquet",
            "audit_meaning": "Vocab-mismatch negatives exist at the broad pair stage.",
            "production_interpretation": "These negatives are ranking decoys, not biological false reactions.",
        },
        {
            "round": ROUND,
            "evidence_item": "clean_full_pos_neg",
            "value": clean_full["y"].value_counts().to_dict(),
            "source_path": "outputs/modular/ltr/clean_candidates_full.parquet",
            "audit_meaning": "Deployment-faithful rule generated candidate pool before final clean candidate filter.",
            "production_interpretation": "Only positives that are generated by rules can be ranked.",
        },
        {
            "round": ROUND,
            "evidence_item": "clean_final_pos_neg",
            "value": clean["y"].value_counts().to_dict(),
            "source_path": "outputs/modular/ltr/clean_candidates.parquet",
            "audit_meaning": "Current final clean candidate training/evaluation table.",
            "production_interpretation": "Most positives never reach the final candidate set.",
        },
        {
            "round": ROUND,
            "evidence_item": "clean_final_positive_retention",
            "value": round(float((clean["y"] == 1).sum()) / float(len(reactions)), 4),
            "source_path": "outputs/modular/ltr/reactions.parquet; outputs/modular/ltr/clean_candidates.parquet",
            "audit_meaning": "Final clean positives divided by unique positive reactions.",
            "production_interpretation": "A low retention rate points to candidate-generation/rule-family coverage limits.",
        },
        {
            "round": ROUND,
            "evidence_item": "clean_metrics_n_pts",
            "value": metrics["n_pts"].value_counts().to_dict(),
            "source_path": "outputs/modular/ltr/clean2_metrics.csv",
            "audit_meaning": "All displayed methods/modules are based on n_pts=10.",
            "production_interpretation": "High 90%/1.00-like numbers are small internal ranking signals, not production proof.",
        },
        {
            "round": ROUND,
            "evidence_item": "round22_p0_route_generation",
            "value": {
                "route_checks": int(len(route)),
                "target_generated": int(route["target_generated"].sum()),
                "final_clean_eligible": int(route["final_clean_eligible_in_dryrun"].sum()),
            },
            "source_path": "data/curation/round22_p0_route_dryrun.csv",
            "audit_meaning": "Round22 checked P0 reactions under multiple rule variants.",
            "production_interpretation": "P0 failures occur before ranking because targets are not generated.",
        },
        {
            "round": ROUND,
            "evidence_item": "round21_p0_family_mix",
            "value": p0["reaction_family"].value_counts().to_dict(),
            "source_path": "data/curation/round21_p0_collection_worklist.csv",
            "audit_meaning": "The P0 misses concentrate in polyphenol/urolithin and dehydroxylation-like chemistry.",
            "production_interpretation": "The user's hypothesis is supported: reaction-type/rule-family gaps are a primary blocker.",
        },
    ]
    return pd.DataFrame(rows)


def ecreact_screen() -> pd.DataFrame:
    src = ROOT / "runtime/external_round23/ecreact_p0_exact_pair_screen_round23.csv"
    if src.exists():
        return pd.read_csv(src)
    p0 = read_table(CUR / "round21_p0_collection_worklist.csv")
    return pd.DataFrame(
        {
            "candidate_id": p0["candidate_id"],
            "ecreact_forward_hits": "not_screened_runtime_cache_missing",
            "ecreact_reverse_hits": "not_screened_runtime_cache_missing",
        }
    )


def build_p0_source_verification() -> pd.DataFrame:
    p0 = read_table(CUR / "round21_p0_collection_worklist.csv")
    route = read_table(CUR / "round22_p0_route_decisions.csv")
    route = route[["candidate_id", "any_target_generated", "decision_round22", "training_allowed_round22"]]
    ecr = ecreact_screen()
    ecr = ecr[
        [
            "candidate_id",
            "ecreact_forward_hits",
            "ecreact_reverse_hits",
            "example_forward_ec",
            "example_reverse_ec",
            "example_forward_source",
            "example_reverse_source",
        ]
    ]
    p0 = p0.merge(route, on="candidate_id", how="left").merge(ecr, on="candidate_id", how="left")

    rhea_61520 = rhea_summary("RHEA_61520.json")
    rhea_urolithin = rhea_summary("urolithin_dehydroxylase.json")
    rhea_proto = rhea_summary("protocatechuate_catechol.json")
    rhea_hca = rhea_summary("hydrocaffeic_acid.json")

    catechol_pmids, catechol_titles = pubmed_titles("catechol_dehydroxylase_gut_esummary.json")
    urolithin_pmids, urolithin_titles = pubmed_titles("urolithin_dehydroxylase_enterocloster_esummary.json")
    hca_pmids, hca_titles = pubmed_titles("hydrocaffeic_dehydroxylase_gordonibacter_esummary.json")
    proto_pmids, proto_titles = pubmed_titles("protocatechuate_decarboxylase_catechol_esummary.json")

    rows = []
    for r in p0.to_dict("records"):
        cid = r["candidate_id"]
        fam = r["reaction_family"]
        if cid == "R21-P0-002":
            rhea_count, rhea_ids, rhea_eqs = rhea_61520
            pmids, titles = catechol_pmids, catechol_titles
            status = "exact_rhea_plus_pubmed_gut_support_but_current_generator_missing_rule"
            next_gate = "find_atom_mapped_rule_in_enzymemap_retrorules_or_derive_from_mapped_exact_reaction"
        elif cid == "R21-P0-009":
            rhea_count, rhea_ids, rhea_eqs = rhea_proto
            pmids, titles = proto_pmids, proto_titles
            status = "exact_rhea_and_ecreact_pair_support_but_gut_context_and_prior_pmid_need_recuration"
            next_gate = "recurate_pmids_then_route_test_rhea_22416_or_ecreact_4_1_1_59_rule_family"
        elif "urolithin" in fam:
            rhea_count, rhea_ids, rhea_eqs = rhea_urolithin
            pmids, titles = urolithin_pmids, urolithin_titles
            status = "pubmed_gut_support_rhea_ecreact_absent_requires_exact_table_and_mapping"
            next_gate = "extract exact substrate_product_rows_from_recent_enterocloster_papers_then_map_structures"
        elif cid == "R21-P0-013":
            rhea_count, rhea_ids, rhea_eqs = rhea_hca
            pmids, titles = hca_pmids, hca_titles
            status = "pubmed_gut_support_with_rhea_related_not_exact_current_generator_missing_rule"
            next_gate = "verify exact hydrocaffeic_to_3_hydroxyphenylpropionate_reaction_and_atom_mapping"
        else:
            rhea_count, rhea_ids, rhea_eqs = 0, "", ""
            pmids, titles = "", ""
            status = "not_sufficiently_rescreened_round23"
            next_gate = "run_targeted_rhea_pubmed_enzymemap_ecreact_query_before_training"

        rows.append(
            {
                "round": ROUND,
                "candidate_id": cid,
                "module": r["module"],
                "reaction_family": fam,
                "reaction_type": r["reaction_type"],
                "substrate_name": r["substrate_name"],
                "product_name": r["product_name"],
                "round22_target_generated": bool(r.get("any_target_generated", False)),
                "round22_decision": r.get("decision_round22", ""),
                "rhea_hit_count_round23": rhea_count,
                "rhea_ids_round23": rhea_ids,
                "rhea_equations_round23": rhea_eqs,
                "pubmed_ids_round23": pmids,
                "pubmed_title_evidence_round23": titles,
                "ecreact_forward_hits_round23": r.get("ecreact_forward_hits", ""),
                "ecreact_reverse_hits_round23": r.get("ecreact_reverse_hits", ""),
                "ecreact_example_forward_ec": r.get("example_forward_ec", ""),
                "ecreact_example_reverse_ec": r.get("example_reverse_ec", ""),
                "source_backed_status_round23": status,
                "training_allowed_round23": False,
                "rule_promotion_allowed_round23": False,
                "next_gate_round23": next_gate,
            }
        )
    return pd.DataFrame(rows)


def build_query_manifest() -> pd.DataFrame:
    rows = []
    rhea_queries = {
        "RHEA_61520.json": "RHEA:61520",
        "dopamine_3_tyramine.json": "dopamine 3-tyramine",
        "catechol_dehydroxylase.json": "catechol dehydroxylase",
        "hydrocaffeic_acid.json": "hydrocaffeic acid",
        "urolithin.json": "urolithin",
        "urolithin_dehydroxylase.json": "urolithin dehydroxylase",
        "protocatechuate_catechol.json": "protocatechuate catechol",
    }
    for file_name, query in rhea_queries.items():
        count, ids, eqs = rhea_summary(file_name)
        rows.append(
            {
                "round": ROUND,
                "source": "Rhea",
                "query": query,
                "raw_path": f"data/curation/rhea_round23_raw/{file_name}",
                "hit_count": count,
                "ids": ids,
                "first_equations_or_titles": eqs,
                "audit_use": "exact reaction database screen",
            }
        )

    pubmed_files = {
        "catechol_dehydroxylase_gut_esummary.json": "catechol dehydroxylase gut microbiota",
        "urolithin_dehydroxylase_enterocloster_esummary.json": "urolithin dehydroxylase Enterocloster",
        "hydrocaffeic_dehydroxylase_gordonibacter_esummary.json": "hydrocaffeic acid dehydroxylase Gordonibacter",
        "protocatechuate_decarboxylase_catechol_esummary.json": "protocatechuate decarboxylase catechol",
    }
    for file_name, query in pubmed_files.items():
        ids, titles = pubmed_titles(file_name)
        rows.append(
            {
                "round": ROUND,
                "source": "NCBI PubMed",
                "query": query,
                "raw_path": f"data/curation/ncbi_round23_raw/{file_name}",
                "hit_count": len(ids.split(",")) if ids else 0,
                "ids": ids,
                "first_equations_or_titles": titles,
                "audit_use": "literature/gut context screen",
            }
        )
    rows.append(
        {
            "round": ROUND,
            "source": "ECReact",
            "query": "exact InChIKey-block substrate/product screen for 14 Round21 P0 candidates",
            "raw_path": "runtime/external_round23/ecreact_p0_exact_pair_screen_round23.csv",
            "hit_count": "",
            "ids": "",
            "first_equations_or_titles": "Only protocatechuic acid -> catechol showed exact forward/reverse pair hits in the local screen.",
            "audit_use": "external broad enzymatic reaction dataset screen",
        }
    )
    return pd.DataFrame(rows)


def build_external_source_candidates() -> pd.DataFrame:
    rows = [
        {
            "round": ROUND,
            "source_name": "Rhea",
            "source_url": "https://www.rhea-db.org/",
            "source_type": "expert_curated_biochemical_reaction_database",
            "usable_positive_fields": "RHEA ID; balanced equation; ChEBI participants; EC/UniProt mappings via Rhea/UniProt",
            "best_use": "High-trust exact reaction validation and ChEBI-normalized positive pairs.",
            "direct_training_role": "gold_or_silver_exact_reaction_if_food_gut_context_also_verified",
            "negative_sample_role": "Do not use absence from Rhea as a hard negative.",
            "main_gate": "Exact substrate/product structure and direction must match; gut/microbial context must be verified separately.",
        },
        {
            "round": ROUND,
            "source_name": "RetroRules",
            "source_url": "https://retrorules.org/docs",
            "source_type": "reaction_template_rule_database",
            "usable_positive_fields": "reaction SMARTS; source reaction; EC; linked compounds; sequences; source dataset",
            "best_use": "Recover missing rule families after exact source reactions are identified.",
            "direct_training_role": "rule_source_or_generator_overlay_candidate_not_direct_gold_label",
            "negative_sample_role": "Rule-generated non-target products can be ranking decoys only after false-negative screen.",
            "main_gate": "Need provenance to exact source reaction and atom-mapping/radius choice.",
        },
        {
            "round": ROUND,
            "source_name": "ECReact",
            "source_url": "https://github.com/rxn4chemistry/biocatalysis-model",
            "source_type": "public_enzymatic_reaction_dataset",
            "usable_positive_fields": "reaction SMILES; EC; source label",
            "best_use": "Broad enzymatic reaction expansion and EC-balanced screening.",
            "direct_training_role": "silver_or_weak_reaction_pair_after_structure_dedup_and_source_check",
            "negative_sample_role": "Use as false-negative screen before labeling generated decoys as hard negatives.",
            "main_gate": "Not gut-specific; source provenance and duplicated/general reactions must be audited.",
        },
        {
            "round": ROUND,
            "source_name": "EnzymeMap",
            "source_url": "https://github.com/hesther/enzymemap",
            "source_type": "atom_mapped_validated_enzymatic_reaction_dataset",
            "usable_positive_fields": "processed reactions; EC; mapped/balanced reaction; optional protein info in v2",
            "best_use": "Derive/validate atom-mapped templates for missing enzyme reaction families.",
            "direct_training_role": "silver_exact_pair_or_rule_derivation_source_after_dedup",
            "negative_sample_role": "False-negative screen and reaction-family neighbor search.",
            "main_gate": "Check version, BRENDA-derived provenance, exact structure mapping, and license/citation.",
        },
        {
            "round": ROUND,
            "source_name": "AGORA2/VMH",
            "source_url": "https://www.vmh.life/",
            "source_type": "human_gut_microbe_metabolic_reconstruction_resource",
            "usable_positive_fields": "reaction IDs; metabolite IDs/structures; strain/taxon model context",
            "best_use": "Gut microbial capacity and taxon-reaction support.",
            "direct_training_role": "contextual_silver_if_exact_reaction_structure_and_source_are_available",
            "negative_sample_role": "Model absence is not a hard negative; can support conditional unknown labels.",
            "main_gate": "Reconstruction evidence is not the same as direct experiment.",
        },
        {
            "round": ROUND,
            "source_name": "gapseq/ModelSEED",
            "source_url": "https://github.com/jotech/gapseq",
            "source_type": "microbial_pathway_prediction_and_reconstruction_tool",
            "usable_positive_fields": "reaction database IDs; pathway assignments; genome-based reaction presence",
            "best_use": "Microbe-specific capacity screens and route-context evidence.",
            "direct_training_role": "contextual_weak_or_silver_only_after_exact_reaction_structure_mapping",
            "negative_sample_role": "Gene/reaction absence is condition-dependent; use as unlabeled/conditional negative only.",
            "main_gate": "Do not convert gap-filled or predicted model reactions into gold positives.",
        },
        {
            "round": ROUND,
            "source_name": "gutMGene",
            "source_url": "https://academic.oup.com/nar/article/53/D1/D783/7850954",
            "source_type": "gut_microbe_metabolite_gene_literature_database",
            "usable_positive_fields": "microbe; substrate/metabolite; gene; PMID; disease/host context",
            "best_use": "Evidence enrichment and literature queue creation.",
            "direct_training_role": "not_direct_reaction_label_unless_exact_substrate_product_reaction_is_recovered",
            "negative_sample_role": "Not a hard negative source.",
            "main_gate": "Associations are not automatically reactions.",
        },
    ]
    return pd.DataFrame(rows)


def build_negative_strategy() -> pd.DataFrame:
    rows = [
        {
            "round": ROUND,
            "negative_type": "within_substrate_rule_decoy",
            "definition": "A product generated by the current rule engine for the same substrate but not the known positive product.",
            "allowed_label": "ranking_decoy_y0_within_candidate_set",
            "not_allowed_claim": "biochemical false reaction",
            "verification_gate": "Screen decoy pair against current positive pool, Rhea, ECReact, EnzymeMap, and curated literature queue before using as hard negative.",
        },
        {
            "round": ROUND,
            "negative_type": "assay_negative",
            "definition": "A paper reports a tested substrate/strain/enzyme condition where the product was not detected.",
            "allowed_label": "condition_specific_negative",
            "not_allowed_claim": "universal biological impossibility",
            "verification_gate": "Must record assay, organism/strain, medium/time, detection method, limit, PMID/DOI, and tested product.",
        },
        {
            "round": ROUND,
            "negative_type": "organism_capacity_negative",
            "definition": "A genome/model lacks the enzyme, gene, pathway, or reaction under a named organism context.",
            "allowed_label": "conditional_unlabeled_or_weak_negative",
            "not_allowed_claim": "hard negative without assay",
            "verification_gate": "Requires genome completeness, annotation method, gene family, model source, and condition scope.",
        },
        {
            "round": ROUND,
            "negative_type": "direction_or_cofactor_invalid",
            "definition": "The proposed pair is incompatible with the source reaction direction, stoichiometry, cofactor logic, or atom conservation.",
            "allowed_label": "chemically_invalid_decoy",
            "not_allowed_claim": "microbial negative",
            "verification_gate": "Check atom balance, Rhea/EnzymeMap direction, cofactors, and current reaction rule direction.",
        },
        {
            "round": ROUND,
            "negative_type": "database_absence",
            "definition": "A pair is not found in Rhea/ECReact/EnzymeMap/current pool.",
            "allowed_label": "unknown",
            "not_allowed_claim": "negative",
            "verification_gate": "Absence is only a search result, never a biological negative.",
        },
    ]
    return pd.DataFrame(rows)


def build_pipeline() -> pd.DataFrame:
    rows = [
        {
            "round": ROUND,
            "stage": 1,
            "stage_name": "collect",
            "action": "Collect candidate reactions by reaction family from Rhea, ECReact, EnzymeMap, RetroRules, AGORA/VMH, gapseq, gutMGene, and targeted PubMed.",
            "output_fields": "source; source_id; substrate_name; product_name; reaction_smiles; ec; enzyme_gene; microbe; pmid; doi; source_url",
            "stop_condition": "No exact substrate/product or no source ID.",
        },
        {
            "round": ROUND,
            "stage": 2,
            "stage_name": "verify_truth",
            "action": "Verify exact reaction identity, direction, structures, atom balance/mapping, and gut/microbial context.",
            "output_fields": "verification_status; exactness_score; structure_status; direction_status; gut_context_status; curator_notes",
            "stop_condition": "Any exactness or structure conflict.",
        },
        {
            "round": ROUND,
            "stage": 3,
            "stage_name": "route_generation_dryrun",
            "action": "Run current generator and candidate rule overlays in dry-run mode only.",
            "output_fields": "target_generated; rule_id; rule_source; decoy_count; false_negative_screen_status",
            "stop_condition": "Target not generated and no source-backed rule/template.",
        },
        {
            "round": ROUND,
            "stage": 4,
            "stage_name": "label_gate",
            "action": "Assign positive, ranking decoy, condition-specific negative, or unknown labels.",
            "output_fields": "label_type; label_scope; label_source; training_allowed; reason",
            "stop_condition": "Unknown evidence cannot become y=0 or y=1.",
        },
        {
            "round": ROUND,
            "stage": 5,
            "stage_name": "summarize_to_csv",
            "action": "Freeze a CSV manifest and Markdown review for each iteration.",
            "output_fields": "iteration; frozen_csv_path; raw_evidence_paths; git_commit; next_query_queue",
            "stop_condition": "Missing raw evidence or uncommitted manifest.",
        },
        {
            "round": ROUND,
            "stage": 6,
            "stage_name": "next_round",
            "action": "Prioritize the next family with largest production impact and strongest source availability.",
            "output_fields": "priority; reaction_family; missing_source; expected_model_impact; risk",
            "stop_condition": "Do not expand random easy reactions that do not repair production route gaps.",
        },
    ]
    return pd.DataFrame(rows)


def build_review_md(paths: dict[str, Path]) -> str:
    return "\n".join(
        [
            "# Round23 Source-backed Sample Expansion Pipeline",
            "",
            "## Working conclusion",
            "",
            "The current production blocker is primarily upstream of the ranker: important reaction families are missing from the candidate-generation/rule layer. The strongest current evidence is Round22: 14 P0 reactions were checked under 56 route variants and none generated the target product.",
            "",
            "This does not mean sample size is irrelevant. It means adding positives alone will not help unless the source-backed reaction family can be generated as a deployment candidate.",
            "",
            "## What changed in this round",
            "",
            "- Added source-backed query raw outputs for Rhea and NCBI PubMed under `data/curation/rhea_round23_raw/` and `data/curation/ncbi_round23_raw/`.",
            "- Screened ECReact in `runtime/external_round23/` and froze the P0 exact-pair summary in a tracked CSV.",
            "- Created explicit gates separating positive samples, ranking decoys, condition-specific negatives, and unknowns.",
            "",
            "## Key findings",
            "",
            "- `dopamine -> m-tyramine` is exact in Rhea as RHEA:61520 and has gut catechol-dehydroxylase literature support, but the current generator still cannot produce the target.",
            "- Urolithin dehydroxylation has recent gut Enterocloster literature support, but Rhea and ECReact did not return exact coverage in this round. It needs paper-table extraction and atom mapping before training.",
            "- `protocatechuic acid -> catechol` is exact in Rhea and ECReact, but gut-specific evidence and prior PMID mismatch still need re-curation before promotion.",
            "- Absence from a database is never a negative label. It is an unknown until a real assay-negative or condition-specific non-production record is found.",
            "",
            "## Generated artifacts",
            "",
            "* `data/curation/round23_current_blocker_audit.csv`",
            "* `data/curation/round23_p0_source_verification.csv`",
            "* `data/curation/round23_source_query_manifest.csv`",
            "* `data/curation/round23_external_training_source_candidates.csv`",
            "* `data/curation/round23_negative_sample_strategy.csv`",
            "* `data/curation/round23_sample_expansion_pipeline.csv`",
            "* `data/curation/round23_ecreact_p0_exact_pair_screen.csv`",
            "",
            "## Production gate",
            "",
            "No Round23 candidate is allowed directly into training. The next production-aligned step is to derive or import source-backed, atom-mapped reaction rules for the missing P0 families, run generation dry-runs, then only promote reactions whose targets are generated and whose labels survive false-negative screening.",
            "",
        ]
    )


def main() -> None:
    paths = {}
    paths["current_blocker"] = write_csv(
        build_current_blocker_audit(), "data/curation/round23_current_blocker_audit.csv"
    )
    paths["p0_source"] = write_csv(
        build_p0_source_verification(), "data/curation/round23_p0_source_verification.csv"
    )
    paths["queries"] = write_csv(
        build_query_manifest(), "data/curation/round23_source_query_manifest.csv"
    )
    paths["sources"] = write_csv(
        build_external_source_candidates(),
        "data/curation/round23_external_training_source_candidates.csv",
    )
    paths["negatives"] = write_csv(
        build_negative_strategy(), "data/curation/round23_negative_sample_strategy.csv"
    )
    paths["pipeline"] = write_csv(
        build_pipeline(), "data/curation/round23_sample_expansion_pipeline.csv"
    )
    ecr = ecreact_screen()
    paths["ecreact"] = write_csv(ecr, "data/curation/round23_ecreact_p0_exact_pair_screen.csv")

    review = ROOT / "docs/reviews/round23_source_backed_sample_pipeline.md"
    review.parent.mkdir(parents=True, exist_ok=True)
    review.write_text(build_review_md(paths), encoding="utf-8")
    paths["review"] = review

    for name, path in paths.items():
        print(f"{name}: {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
